application:
  queue:
    jmsBrokerUrl: tcp://localhost:61616
    jmsQueueName: workItems
    receiveTimeout: 1
  producer:
    workingDirectories: F:\\Data\\test folder 1;F:\\Data\\test folder 1 - Copy

spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 10
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: FileSystemHashCache
